services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_USER: db            # Assigning user directly
      POSTGRES_PASSWORD: db  # Assigning password directly
      POSTGRES_DB: db             # Name of the database
      POSTGRES_PORT: 5432          # Port on which PostgreSQL listens

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db            # Assigning user directly
      POSTGRES_PASSWORD: db  # Assigning password directly
      POSTGRES_DB: db             # Name of the database
      POSTGRES_PORT: 5432          # Port on which PostgreSQL listens

volumes:
  pgdata: