services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_PORT: ${POSTGRES_PORT}
      - POSTGRES_HOST: ${POSTGRES_HOST}

volumes:
  pgdata: