version: "2.1"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - dvna-network

  postgres-db:
    build:
      context: ./
      dockerfile: Dockerfile-DB
    expose:
      - "5432:5432"
    networks:
      - dvna-network

networks:
    dvna-network:
        driver: bridge