name: TP2 CI

on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bcrypt
        run: npm install bcrypt@latest
      - name: Install
        run: npm install
      - name: Snyk
        # You may pin to the exact commit or the version.
        # uses: snyk/actions@b98d498629f1c368650224d6d212bf7dfa89e4bf
        uses: snyk/actions@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true
      # - name: Official SonarQube Scan
      #   # You may pin to the exact commit or the version.
      #   # uses: SonarSource/sonarqube-scan-action@884b79409bbd464b2a59edc326a4b77dc56b2195
      #   uses: SonarSource/sonarqube-scan-action@v3.0.0
          